CREATE TABLE [dbo].[WorkEnvelope](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[X] [int] NULL,
	[Y] [int] NULL,
	[ANGLE] [int] NULL,
 CONSTRAINT [PK_WorkEnvelope] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

